### ISSUE TITLE
Firefox Peer Review

### ISSUE THREAD

**Issue by motin** [mozilla/preparatory-survey-for-naar-study-addon#2]
This study add-on includes a web extension experiment that simulates a Heartbeat prompt, based on Heartbeat.jsm ([see expected UX and functionality here](https://github.com/mozilla/preparatory-survey-for-naar-study-addon/blob/master/docs/TESTPLAN.md#expected-user-experience--functionality))
@mythmon Would you mind peer reviewing this study add-on? Here is a commit with all the add-on code and tests for the review: https://github.com/mozilla/preparatory-survey-for-naar-study-addon/commit/dc47d2012083b30377ed8d75818551f901782858

**Comment by mythmon** [comment]
I am not a Firefox peer. I can review the code, but that wouldn't satisfy the requirement that study add-ons be reviewed by a Firefox peer.

**Comment by motin** [comment]
> I am not a Firefox peer. I can review the code, but that wouldn't satisfy the requirement that study add-ons be reviewed by a Firefox peer.

Ah, my mistake. Thanks for the reminder. In that case: @rhelmer, could you take a look?

**Comment by rhelmer** [comment]
I am out today but could do it on Monday. @biancadanforth is a peer and has more experience with study add-ons so if she has time to take a look I am happy to defer :)

**Comment by motin** [comment]
@biancadanforth, feel free to take a look if you have time :)

**Comment by rhelmer** [comment]
lgtm, left comments on the commit. Nice work!

**Comment by biancadanforth** [comment]
I was also out Friday, and I am getting a late start today. Glad it was resolved.
