### ISSUE TITLE
The "Preparatory Survey for NAAR" add-on is not uninstalled after the study ends

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/preparatory-survey-for-naar-study-addon#3]
[Notes]:
- The issue is reproducible in the following scenarios:
	- The survey is taken.
	- The Heartbeat-styled notification bar is dismissed.
	- The Heartbeat-styled notification bar is ignored and the browser is restarted twice.
	- The Heartbeat-styled notification bar is ignored for more than 1 day.
- After each Firefox restart, the Preparatory Survey for NAAR extension runs again and the Heartbeat-styled notification bar is redisplayed, even if the study ended.
- The "ended-neutral/expired" and "exit" telemetry pings are correctly sent after the study ends.

[Affected Versions]:
- Preparatory Survey for NAAR 1.0.0

[Affected Platforms]
- All Windows
- All Mac
- All Linux

[Prerequisites]
- Have the latest Firefox 68 unbranded build installed.
- Have at least 3 add-ons installed from AMO.
- Have the "shieldStudy.logLevel" string pref created with "info" value.
- Have the "xpinstall.signatures.dev-root" boolean pref created with the "true" value.
- Have the "xpinstall.signatures.required" boolean pref set to "false".
- Have the Preparatory Survey for NAAR 1.0.0 signed xpi installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the "Take me to the questionnaire" button from the displayed Heartbeat-styled notification bar. 
3. Complete and submit the survey.
4. Restart the browser and navigate to "about:support" page.
5. Observe the "Extensions" section.

[Expected results]:
- The Preparatory Survey for NAAR extension is uninstalled and is no longer listed.

[Actual results]:
- The Preparatory Survey for NAAR extension is still installed and the Heartbeat-styled notification bar is redisplayed.

[Additional Notes]:
- Attached a screen recording with the issue.
![not uninstalled](https://user-images.githubusercontent.com/19226534/60435465-4e638480-9c12-11e9-9278-bf9f44682dca.gif)

**Comment by motin** [comment]
Thanks @SoftVision-CosminMuntean, this is not caught by the current set of automated tests! There is some sort of error seemingly related to removeSheet inside the Heartbeat clean-up code. Using try/catch doesn't bite - the best I get is `uncaught exception: Object`.
@mythmon, do you better understand what is going on here?

**Comment by mythmon** [comment]
Looking at the code, I don't see anything obviously wrong. Can I see the version of the code that you tested the `try/catch` behavior with? Specifically, where are you trying to catch the error?

It would also be useful to figure out just what that exception is. Maybe it is something that we can safely ignore. If that's the case, we can restructure the function to always finish even if the heartbeat CSS can't be removed.

**Comment by motin** [comment]
Fixed in https://github.com/mozilla/preparatory-survey-for-naar-study-addon/commit/f823332dea458f7b229931039f1d1b4099cac62d
This was indeed confusing. The `uncaught exception: Object` is not related to this study add-on, it shows up in the browser console even after the fix. The removeSheet error that is shown in the above screen recording has nothing to do with the error neither (not sure why it was reported since the code related to removeSheet was not firing at all). Rather it was a mismatch between the code and the web ext experiment api class that was at fault - something that was not reported in the browser console (with could be caught in add-on Inspect mode).

**Comment by motin** [comment]
@mythmon, thanks for checking. Your comment made me look elsewhere and find the real culprit :)

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the Preparatory Survey for NAAR unsigned build (v1.0.1) and is no longer reproducible. The add-on is uninstalled after the study ends.

Tested on Windows 7 x64, Mac 10.14 and Arch Linux 4.12.
