### ISSUE TITLE
[Survey] The "Mozilla Privacy" wrongly opens in the same tab after clicking the "Mozilla Privacy Policy" link

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/preparatory-survey-for-naar-study-addon#4]
**[Notes]:**
- If the browser's "Back" button is clicked after the "Mozilla Privacy" website is opened from the second or third survey page, the "Document Expired" page is displayed. However, if the page is refreshed or the "Try again" button is clicked, the survey page is redisplayed.

**[Affected versions]:**
- Preparatory Survey for NAAR 1.0.0

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the latest Firefox 68 unbranded build installed.
- Have at least 3 add-ons installed from AMO.
- Have the "xpinstall.signatures.dev-root" boolean pref created with the "true" value.
- Have the "xpinstall.signatures.required" boolean pref set to "false".
- Have the Preparatory Survey for NAAR 1.0.0 signed xpi installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Take me to the questionnaire" button from the displayed Heartbeat-styled notification bar.
3. Click the "Mozilla Privacy Policy" link from the second page displayed.
4. Observe the behavior.

**[Expected result]:**
- The "Mozilla Privacy" website is opened in a new tab. 

**[Actual result]:**
- The "Mozilla Privacy" website is opened in the same tab.

**[Additional Notes]:**
- Attached a screen recording with the issue:
![Expired](https://user-images.githubusercontent.com/40061643/60522396-8e4d6900-9cf1-11e9-8cac-3664133525b6.gif)

**Comment by Softvision-RemusDranca** [comment]
I am sorry for misleading you with the title for this issue. I updated it accordingly.

**Comment by motin** [comment]
Thanks @Softvision-RemusDranca, this is indeed non very user-friendly and could lead to survey abandonment. I have updated the Privacy Policy link to open in a new window.
I also found a bug in the survey code thanks to this report. Reported as https://github.com/mozilla/preparatory-survey-for-naar-study-addon/issues/5 - the opening in the same window bug applied to that link too but have been fixed as well.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible for the "Mozilla Privacy Policy" link, when clicked the website opens in a new tab.

However, after further testing it seems that the issue is also reproducible for the "support.mozilla.org", "feedback page" and "Mozilla Newsletter" links from the third page (Thank you page) of the Survey.

**Comment by motin** [comment]
> However, after further testing it seems that the issue is also reproducible for the "support.mozilla.org", "feedback page" and "Mozilla Newsletter" links from the third page (Thank you page) of the Survey.

As that is the last page, the desired action is that the user leaves the survey, so opening these links in the same window is desirable behavior.
