### ISSUE TITLE
[Survey] The telemetry disclaimer is not displayed on the second and third page of the survey

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/preparatory-survey-for-naar-study-addon#6]
**[Notes]:**
- If the "Back" button is clicked when the user is on the second page of the survey, the telemetry disclaimer is no longer displayed on the first page as well.

**[Affected versions]:**
- Preparatory Survey for NAAR 1.0.1

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the latest Firefox 68.0b14 unbranded build installed.
- Have at least 3 add-ons installed from AMO.
- Have the "xpinstall.signatures.dev-root" boolean pref created with the "true" value.
- Have the "xpinstall.signatures.required" boolean pref set to "false".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and install the Preparatory Survey for NAAR 1.0.1 signed build.
2. Click the "Take me to the questionnaire" button from the displayed Heartbeat-styled notification bar.
3. Complete the required questions with valid data for each add-on.
4. Click the "Next" button and observe the bottom of the page.

**[Expected result]:**
- The telemetry disclaimer is displayed under the "Mozilla Privacy Policy" section. 

**[Actual result]:**
- The telemetry disclaimer is not displayed.

**[Additional Notes]:**
- Attached a screen recording with the issue:
![telemetryDisclaimer](https://user-images.githubusercontent.com/40061643/60728480-11b4c780-9f49-11e9-883d-60657560934c.gif)

**Comment by motin** [comment]
Thanks, this is indeed a general issue with multi-page surveys in SurveyGizmo since we only show the disclaimer if specific url variables are present - and they are never present on page 2+.
Fixed by hard-coding to display the disclaimer for this survey.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and is no longer reproducible. The telemetry disclaimer is now displayed on all survey pages.
Tested on Windows 10 x64, Mac 10.14 and Ubuntu 16.04.
