### ISSUE TITLE
The "Preparatory Survey for NAAR" experiment is wrongly displayed as active in "about:studies" page after it is removed

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/preparatory-survey-for-naar-study-addon#7]
**[Notes]:**
- If the page is refreshed, the "Preparatory Survey for NAAR" experiment will be displayed in the "Completed studies" section.

**[Affected versions]:**
-  Firefox 68.0b14 unbranded

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a recipe created for the experiment on the Normandy stage server ([link to recipe](https://delivery-console.stage.mozaws.net/recipe/781/)).
- Have the latest Firefox 68.0b14 unbranded build installed.
- Have at least 3 add-ons installed from AMO.
- Have the following prefs set in “about-config” page:
    - The "xpinstall.signatures.dev-root" boolean pref with the "true" value.
    - The “app.normandy.dev_mode preference” to “true” to run recipes immediately on startup.
    - The “app.normandy.logging.level preference” to “0” to enable more logging.
    - The “security.content.signature.root_hash” preference to “DB:74:CE:58:E4:F9:D0:9E:E0:42:36:BE:6C:C5:C4:F6:6A:E7:74:7D:C0:21:42:7A:03:BC:2F:57:0C:8B:9B:90”.
     - The “services.settings.server” to “https://normandy.stage.mozaws.net/api/v1”.
     - The “extensions.shield-recipe-client.api_url” to “https://stage.normandy.nonprod.cloudops.mozgcp.net/api/v1”.
   
**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to the "about:studies" page.
3. Click the "Remove" button for the “Preparatory Survey for NAAR” experiment and observe the behavior.

**[Expected result]:**
- The experiment is instantly moved to the "Completed studies" section. 

**[Actual result]:**
- The experiment is still displayed in the "Active studies" section. 

**[Additional Notes]:**
- The following error message is displayed in the Browser's Console: "Error: Cannot stop study for recipe 781; it is already inactive.".
- Nothing happens if the "Remove" button is clicked multiple times, the experiment remains in the "Active studies" section.
- However, the notification bar is no longer displayed after clicking the "Remove" button and the correct telemetry pings are sent.
- This issue was not reproducible for other add-on experiments we tested.
- Attached a screen recording with the issue:
![aboutStudiesRemove](https://user-images.githubusercontent.com/40061643/60904408-abe37b00-a27b-11e9-9c82-71362d18f89f.gif)

**Comment by motin** [comment]
I don't suspect that this is an issue that stems from this add-on itself, but maybe @mythmon can shine a light upon this? Should I transfer the issue to the Normandy repo or is there something in the manifest/configuration that should be corrected?

**Comment by motin** [comment]
Aha, it complains about setTimeout not being defined. This is [code](https://github.com/mozilla/shield-studies-addon-utils/pull/290/files#diff-b53f38e6ed1b5be098ff50680fcac759R135) in a version of the utils library which we will deprecate soon. Transferring to the utils repo...
